# Edge/Ingress Layer
# Handles external traffic, SSL certificates, and routing

volumes:
  certbot_etc:

networks:
  bankapp-infra:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    networks:
      - bankapp-infra
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}

  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    command: >
      certonly
      --dns-cloudflare
      --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini
      --dns-cloudflare-propagation-seconds 60
      --email certbot@bankapp.online
      --agree-tos
      --non-interactive
      --domains *.bankapp.online
      --domains bankapp.online
      --expand
    restart: "no"  # Only run once, not continuously

  nginx:
    image: nginx:1.29.0
    container_name: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_etc:/etc/letsencrypt
      - ../auth-frontend:/var/www/auth-fe
    networks:
      - bankapp-infra
    restart: unless-stopped
    depends_on:
      cloudflared:
        condition: service_started
      certbot:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3


